# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-03 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='余额')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='用户余额更新时间')),
            ],
            options={
                'verbose_name': '余额积分表',
            },
        ),
        migrations.CreateModel(
            name='GetMoneyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='金额')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户提现表',
            },
        ),
        migrations.CreateModel(
            name='ShangmiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255, verbose_name='openid')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('nick_name', models.CharField(max_length=30, null=True, verbose_name='昵称')),
                ('source', models.CharField(max_length=30, verbose_name='用户来源')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='店铺名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shangmi.ShangmiUser', verbose_name='店老板')),
            ],
        ),
        migrations.AddField(
            model_name='getmoneylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shangmi.ShangmiUser', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shangmi.ShangmiUser', verbose_name='用户'),
        ),
    ]
