# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-03 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shangmi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='活动名字')),
                ('icon', models.CharField(max_length=255, verbose_name='海报封面')),
                ('desc', models.CharField(max_length=255, verbose_name='活动描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('give_money', models.IntegerField(verbose_name='活动给予积分')),
            ],
            options={
                'verbose_name': '活动表',
            },
        ),
        migrations.CreateModel(
            name='ActiveStoreMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shangmi.Active', verbose_name='活动')),
            ],
            options={
                'verbose_name': '活动与门店关系表',
            },
        ),
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='海报名字')),
                ('icon', models.CharField(max_length=255, verbose_name='海报封面')),
                ('affect_time', models.DateField(null=True, verbose_name='截止日期')),
            ],
            options={
                'verbose_name': '海报',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='activestoremap',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shangmi.Store', verbose_name='门店'),
        ),
        migrations.AlterUniqueTogether(
            name='activestoremap',
            unique_together=set([('store', 'active')]),
        ),
    ]
