# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-04 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangmi', '0002_auto_20181103_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='is_fast',
            field=models.BooleanField(default=True, verbose_name='是否快速'),
        ),
    ]
