# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-22 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangmi', '0006_auto_20181107_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='complete_num',
            field=models.IntegerField(default=0, verbose_name='完成量'),
        ),
        migrations.AddField(
            model_name='active',
            name='need_num',
            field=models.IntegerField(default=0, verbose_name='活动总量'),
        ),
    ]
