# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-09 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangmi', '0011_auto_20181208_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaylog',
            name='order_num',
            field=models.CharField(max_length=255, null=True, verbose_name='咱们自己的订单编号'),
        ),
        migrations.AlterField(
            model_name='userpaylog',
            name='integral',
            field=models.IntegerField(null=True, verbose_name='使用的积分数'),
        ),
        migrations.AlterField(
            model_name='userpaylog',
            name='money',
            field=models.IntegerField(null=True, verbose_name='差价钱数'),
        ),
    ]
