# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-10 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangmi', '0013_userpaylog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='boss_phone',
            field=models.CharField(max_length=15, null=True, verbose_name='授权手机号'),
        ),
    ]
