# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-12 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangmi', '0016_auto_20181211_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='notice',
            field=models.BooleanField(default=True, verbose_name='是否接收通知'),
        ),
    ]
