# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-12 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shangmi', '0017_store_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(verbose_name='充值金额')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='参加时间')),
                ('is_ok', models.BooleanField(default=False, verbose_name='充值状态')),
                ('wx_pay_num', models.CharField(max_length=255, verbose_name='微信支付订单号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shangmi.ShangmiUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户充值',
            },
        ),
    ]
