# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-12 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shangmi', '0018_userrecharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreActiveBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0, verbose_name='活动金余额')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='参加时间')),
                ('active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shangmi.Active')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shangmi.Store', verbose_name='门店')),
            ],
        ),
        migrations.AlterField(
            model_name='userrecharge',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
