# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-09 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangmi', '0026_auto_20190108_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='getmoneylog',
            name='target',
            field=models.CharField(default='微信零钱', max_length=50),
        ),
    ]
