# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-18 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangmi', '0029_auto_20190116_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='free_date',
            field=models.DateField(null=True, verbose_name='免费使用到期时间'),
        ),
    ]
