# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-27 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangmi', '0030_store_free_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='active',
            name='detail_icon',
            field=models.CharField(max_length=255, null=True, verbose_name='详情图片'),
        ),
    ]
