# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-04 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shangmi', '0031_auto_20190127_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='优惠券名字')),
                ('money', models.IntegerField(verbose_name='优惠券面值')),
                ('can_use', models.IntegerField(verbose_name='使用条件')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('over_time', models.DateField(null=True, verbose_name='优惠券领取结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('desc', models.CharField(max_length=255, verbose_name='积分描述')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shangmi.Store', verbose_name='关联的门店')),
            ],
            options={
                'verbose_name': '门店积分券',
            },
        ),
        migrations.CreateModel(
            name='UserGetCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='领取时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shangmi.Coupon', verbose_name='优惠券')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shangmi.ShangmiUser', verbose_name='用户')),
            ],
        ),
    ]
