# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-11 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shangmi', '0032_coupon_usergetcoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='boss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shangmi.ShangmiUser', verbose_name='店老板'),
        ),
    ]
