# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-13 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangmi', '0034_baoxiandata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baoxiandata',
            name='use_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='使用时间'),
        ),
    ]
