# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-13 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangmi', '0035_auto_20190213_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='baoxiandata',
            name='is_used',
            field=models.BooleanField(default=0, verbose_name='是否被使用'),
        ),
    ]
