# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-13 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangmi', '0036_baoxiandata_is_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaoxianData_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='人名')),
                ('phone', models.CharField(max_length=13, verbose_name='手机号')),
                ('idcard', models.CharField(db_index=True, max_length=30, verbose_name='身份证')),
                ('is_ok', models.BooleanField(default=False)),
                ('use_time', models.DateTimeField(auto_now=True, null=True, verbose_name='使用时间')),
                ('fail_msg', models.CharField(max_length=255, null=True, verbose_name='失败原因')),
                ('is_used', models.BooleanField(default=0, verbose_name='是否被使用')),
            ],
            options={
                'db_table': 'baoxian_data_1',
            },
        ),
    ]
