# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-19 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangmi', '0037_baoxiandata_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecharge',
            name='recharge_type',
            field=models.CharField(default='现金充值', max_length=20),
        ),
    ]
