# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-04 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangmi', '0040_errorlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorLog',
        ),
        migrations.AddField(
            model_name='store',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='门店余额'),
        ),
        migrations.AddField(
            model_name='store',
            name='get_money_pwd',
            field=models.CharField(max_length=255, null=True, verbose_name='提现密码'),
        ),
    ]
